In [1]:
import sys
sys.path.insert(0, "..")

import pandas as pd

from diaphanous.show import show


df = pd.read_csv("../data/ocse-report-recipients.csv", thousands=",")
df = (
    df.groupby(["year", "level_of_detail"])
    .sum()
    .drop(columns="recipients")
)

df["totals"] = df.groupby("year").transform(lambda g: g.sum())
df["reports_pct"] = df["reports"] / df["totals"] * 100
show(df)